name: Auto PR for v2 branches

on:
  push:
    branches:
      - 'v2-*'
      - 'v2-work'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          title: "v2 — Ajustes: ${{ github.ref_name }}"
          body: |
            Resumo das alterações geradas pela branch `${{ github.ref_name }}`:

            - Reestruturação e ajustes nas páginas relacionadas à V2 (ex.: index, cadastro, projetos, sistema).
            - Atualizações em estilos e scripts conforme necessário.

            Commit de referência: `${{ github.sha }}`

            Solicito revisão rápida e merge quando aprovado.
          draft: false
